### ISSUE TITLE
Question of Behaviour Sequence Length on Public Dataset

### ISSUE THREAD

**Issue by djx2726889** [facebookresearch/generative-recommenders#39]
On the public MovieLens 1M or MovieLens 20M dataset, the average length of behavior sequences is around 150, which is significantly less than 8192. I am curious whether this dataset is suitable for evaluating the benefits of long sequence modeling using HSTU.

**Comment by jiaqizhai** [comment]
We agree that the lengths of data in such datasets make them less ideal for testing long sequences performance, which is why all long sequence studies in our initial paper (Section 4.2+) are done based on Meta's internal datasets.  Having  publicly usable versions of recommendation dataset with say 4k+ sequence lengths would be very valuable for research purposes. If people have thoughts on how to approach this in a way that respects privacy and is compliant with regulations etc (eg maybe synthesize some artificial datasets?), we are happy to collaborate as well; please reach out to us via email :)
